# -----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <bonecrusher@covenofchaos.com>  wrote this file.  As long as  you retain this
# notice you can do whatever you want with this stuff.  If we meet some day and
# you think this stuff is worth it, you can buy me a beer in return.
#  > BoneCrusher <
# -----------------------------------------------------------------------------

export enki_location=${(%):-%N}

enki_location=`readlink $enki_location`
enki_location=`dirname $enki_location`
enki_location=$enki_location/..

# No longer using oh-my-zsh
# export omz_custom_location=${enki_location}/.omz-custom
# export ohmyzsh_location=${enki_location}/.oh-my-zsh

# POWERLEVEL9K_MODE='nerdfont-complete'
# source ~/.zprezto/modules/prompt/external/powerlevel9k/powerlevel9k.zsh-theme

source ${enki_location}/scripts/source/source_my_scripts.zsh

[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true
stty -ixon

autoload -Uz compinit
compinit

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="/Users/pat/.sdkman"
#[[ -s "/Users/pat/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/pat/.sdkman/bin/sdkman-init.sh"

source ~/.iterm2_shell_integration.zsh

iterm2_print_user_vars() {
  iterm2_set_user_var gitBranch $((git branch 2> /dev/null) | grep \* | cut -c3-)
  iterm2_set_user_var badge $(dir_badges)
  iterm2_set_user_var camel $(is_it_wednesday)
  iterm2_set_user_var nodeVersion $(node -v)
}

function is_it_wednesday() {
  if [[ $(date +%A) = "Thursday" ]]
    then
     echo "🐪" # Camel Prompt
  else
    echo "🐙" # Inky Prompt
  fi
}

function dir_badges() {
    while read directory badge || [[ -n "$directory" ]]
    do
        if [[ "$PWD" == $directory* ]]; then
            echo $badge
            break
        fi
    done < ~/.badges
}

# export PATH="/usr/local/opt/llvm/bin:$PATH"

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
#[[ -f /Users/pat/.asdf/installs/nodejs/12.2.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/pat/.asdf/installs/nodejs/12.2.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
#[[ -f /Users/pat/.asdf/installs/nodejs/12.2.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/pat/.asdf/installs/nodejs/12.2.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
#[[ -f /Users/pat/.asdf/installs/nodejs/12.2.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/pat/.asdf/installs/nodejs/12.2.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh

#eval "$(rbenv init -)"

# This was from kernel class
#export SOLUTIONS=/home/pat/LFT/LFD435/SOLUTIONS

#if [[ -f $SOLUTIONS/s_04/LFD_bashrc ]]; then
#	source $SOLUTIONS/s_04/LFD_bashrc
#fi

#alias genmake='KROOT=$HOME/Projects/class/linux-4.20 $SOLUTIONS/genmake'
#alias make_install='make && sudo make ARCH=arm INSTALL_MOD_PATH=/srv/bbb modules_install'

alias icat="kitty +kitten icat"

[[ -f /Users/pat/.asdf/installs/nodejs/12.9.1/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/pat/.asdf/installs/nodejs/12.2.0/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh

# Remove the duplicate
normalize_path