export enki_location=${(%):-%N}

enki_location=`readlink $enki_location`
enki_location=`dirname $enki_location`
enki_location=$enki_location/..

export omz_custom_location=${enki_location}/.omz-custom
export ohmyzsh_location=${enki_location}/.oh-my-zsh

source ${enki_location}/scripts/source/source_my_scripts

load-node-env

export JENKINS_CREDS=plaplante:410b7e7a847169abd33394a6e600721d
