#!/usr/bin/env bash

set -e
cwd=$(pwd)
function finish { cd "${cwd}"; };
trap finish EXIT

adb root    &>/dev/null
adb remount &>/dev/null
adb root    &>/dev/null
adb remount &>/dev/null

adb shell "camera-phoenix-test $*"

