#!/usr/bin/env zsh

# -----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <bonecrusher@covenofchaos.com>  wrote this file.  As long as  you retain this
# notice you can do whatever you want with this stuff.  If we meet some day and
# you think this stuff is worth it, you can buy me a beer in return.
#  > BoneCrusher <
# -----------------------------------------------------------------------------

# You have to use npm to install npm, and that will give you the
# completionaphe.sh file you need.
#source /opt/local/lib/node_modules/npm/lib/utils/completion.sh

alias npm-pop='npm outdated -g --depth=0'
alias npm-pupd='npm update -g'
alias npm-lg="npm list -g --depth=0 2>/dev/null"
alias npm-ll="npm list --depth=0 2>/dev/null"

function nvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use  # This loads nvm
  [[ -r $NVM_DIR/bash_completion ]] && \. $NVM_DIR/bash_completion

  nvm "$@"
}

function node() {
  unfunction node
  nvm use 11.4
  node "$@"
}

